name: Preview Codespace

on:
  pull_request:
    types: [labeled, unlabeled]

env:
  FORWARDED_PORT: 8000
  PREVIEW_LABEL: "run-codespace" # Change this to customise the trigger label

jobs:
  manage-codespace:
    # Only run the job when the configured preview label itself is added or removed
    if: github.event.label.name == 'run-codespace'
    runs-on: ubuntu-latest

    steps:
      - name: Run Codespace Manager
        uses: b4m11/prevue@v1
        with:
          codespaces_pat: ${{ secrets.PREVUE_KEY }}
          pr_number: ${{ github.event.pull_request.number }}
          forwarded_port: ${{ env.FORWARDED_PORT }}
          labels_json: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          label: ${{ env.PREVIEW_LABEL }} # Optional — defaults to 'preview-url'